# Overrides to enable python-tool-assisted generations across pipelines.

stages:
  filter_problems:
    problem_field: null
    problem_template: "{_filled_prompt}"
    num_options_field: num_options
    diversity_prompts_path: /nemo_run/code/recipes/opensciencereasoning/sdg_pipeline/prompt/diversity_prompts/mcq_various_formats.jsonl
    diversity_prompts_prompt_key: user_prompt
    diversity_prompts_answer_regex_key: output_regex
  generate_solutions:
    prompt_config: ++prompt_config=/nemo_run/code/recipes/opensciencereasoning/sdg_pipeline/prompt/configs/default_problem.yaml ++inference.tokens_to_generate=60000 ++inference.temperature=1.0 ++inference.top_p=1.0
    predicted_answer_regex_field: answer_regex
    generation_kwargs:
      args:
        input_file: ${base_output_dir}/solution-sdg/step-0-filter-problems/final_result.jsonl
  decontaminate:
    enabled: False
  topics_labeling:
    enabled: False
  difficulty_estimation:
    enabled: False
  aggregate:
    enabled: False
  filter_solutions:
    input_file: ${base_output_dir}/solution-sdg/step-4-generate-solutions/final_result.jsonl
  
    
