# Prompt used for text-to-SQL

system: Please reason step by step, and put your final answer within the tags "```sql" and "```".

user: |-
  ### Question
  {question}

  The following is a SQL dump that describes the database and the tables in it.
  {sql_context}

  Convert the question above to a SQL query for the database given. Use the answer tags given.
  If there is more than one set of tags, the last one will be taken as your final answer.

  ### Answer:
