# default prompt for all python based code benchmark evaluations
# https://github.com/NVIDIA-NeMo/Skills/blob/main/nemo_skills/prompt/config/generic/codegen.yaml
user: |-
  Here is a problem for which you need to generate/complete code:
  {question}

  Please continue to complete the function with python programming language. You are not allowed to modify the given code and do the completion only.

  The solution should be in the following format:
  ```python
  # Your code here
  ```
