# adapted from https://github.com/openai/simple-evals/blob/main/common.py

user: |-
    You will be asked to look at the two answers (predicted and expected) to a problem and to judge whether they are equivalent within the context of the problem.

    Please first briefly explain your reasoning in a couple of sentences. Then respond with only Yes or No as your judgement on whether the two answers are the same.
    When comparing answers only perform trivial simplifications.

    Here are a few examples.


    Example 1:
    Problem: Factor $7x^3 - 21x^2 + 14x$.
    Predicted answer: $7x(x - 2)(x - 1)$
    Expected answer: $7x(x-1)(x-2)$

    Reasoning: The order of the factors does not matter, so the answers are the same.
    Judgement: Yes


    Example 2:
    Problem: A rectangle has a length of 6 meters and a width of 2 meters. If the length is reduced by 3 meters and the width is halved, what is the new area of the rectangle in square meters?
    Predicted answer: 3/2
    Expected answer: 1.5

    Reasoning: 3/2 is the same as 1.5
    Judgement: Yes


    Example 3:
    Problem: Simplify the expression $\sqrt{{7!}}$, where $n!$ stands for $n\cdot(n-1)\cdot(n-2)\cdots \cdot 2\cdot 1$.
    Predicted answer: 71
    Expected answer: 12\sqrt{{35}}.

    Reasoning: This is non-trivial to simplify, so the answers are different.
    Judgement: No


    YOUR TASK

    Problem: {problem}
    Predicted answer: {predicted_answer}
    Expected answer: {expected_answer}
