gpqa:
  - prompt_config: robustness/mcq_prompts/aai_1
  - prompt_config: robustness/mcq_prompts/aai_2
  - prompt_config: robustness/mcq_prompts/boxed_1
  - prompt_config: robustness/mcq_prompts/boxed_2
  - prompt_config: robustness/mcq_prompts/correct_1
    extract_regex: '(?i)The correct answer choice is\:*\**\s*\**([A-Za-z])'
  - prompt_config: robustness/mcq_prompts/correct_2
    extract_regex: '(?i)The correct answer choice is\:*\**\s*\**([A-Za-z])'
  - prompt_config: robustness/mcq_prompts/final_answer_1
    extract_regex: '(?i)Final answer\b[\s\n\*\-–—\[:]*([A-Z])\b'
  - prompt_config: robustness/mcq_prompts/final_answer_2
    extract_regex: '(?i)Final answer\b[\s\n\*\-–—\[:]*([A-Z])\b'
  - prompt_config: robustness/mcq_prompts/angle_brackets_1
    extract_regex: '<<([A-Za-z])>>'
  - prompt_config: robustness/mcq_prompts/angle_brackets_2
    extract_regex: '<<([A-Za-z])>>'


comp-math-24-25:
  - prompt_config: robustness/math_prompts/boxed_1
  - prompt_config: robustness/math_prompts/boxed_2
  - prompt_config: robustness/math_prompts/boxed_3
  - prompt_config: robustness/math_prompts/boxed_4
  - prompt_config: robustness/math_prompts/boxed_5
  - prompt_config: robustness/math_prompts/boxed_6
  - prompt_config: robustness/math_prompts/boxed_7
  - prompt_config: robustness/math_prompts/boxed_8
  - prompt_config: robustness/math_prompts/boxed_aai
  - prompt_config: robustness/math_prompts/boxed_general


livecodebench:
  - prompt_config: robustness/code_prompts/aai_prompt
  - prompt_config: robustness/code_prompts/ns_gen_codegen
  - prompt_config: robustness/code_prompts/ns_python_codegen
  - prompt_config: robustness/code_prompts/code_1
  - prompt_config: robustness/code_prompts/code_2
  - prompt_config: robustness/code_prompts/code_3
  - prompt_config: robustness/code_prompts/code_4
