# SFT Algorithm Configuration
sft:
  ## total number of steps to train will equal
  ## min((max_num_epochs * len(train_dataloader)), max_num_steps)
  # setting both to big values by default, so only one needs to be set
  max_num_epochs: 100000000
  max_num_steps: 100000000

  val_period: 0
  val_batches: 1
  val_global_batch_size: 32
  val_micro_batch_size: 1
  val_at_start: false
  seed: 42

checkpointing:
  enabled: true
  checkpoint_dir: "results/sft"
  metric_name: "train_loss"
  higher_is_better: false
  keep_top_k: 50
  save_period: 100
  checkpoint_must_save_by: null


policy:
  model_name: ???
  tokenizer:
    name: ${policy.model_name} ## specify if you'd like to use a tokenizer different from the model's default
    chat_template: "infer_from_data"  ## Can be: null (passthrough), "default" (tokenizer's default), "infer_from_data" (auto-detect from data), or custom jinja2 template
    chat_template_kwargs: null # can be used to pass kwargs to the chat template, e.g., enable_thinking=true
  train_global_batch_size: 32
  train_micro_batch_size: 1
  max_total_sequence_length: 4096
  precision: "bfloat16"
  fsdp_offload_enabled: false
  offload_optimizer_for_logprob: false
  activation_checkpointing_enabled: false
  tensor_model_parallel_size: 1
  pipeline_model_parallel_size: 1
  context_parallel_size: 1
  sequence_parallel: true
  lr: 1e-6
  weight_decay: 0.01
  min_lr: 1e-6


  dtensor_cfg:
    enabled: true
    cpu_offload: False
    sequence_parallel: ${policy.sequence_parallel}
    activation_checkpointing: false
    tensor_parallel_size: ${policy.tensor_model_parallel_size}
    context_parallel_size: ${policy.context_parallel_size}
    custom_parallel_plan: null


  megatron_cfg:
    enabled: true
    empty_unused_memory_level: 0
    activation_checkpointing: true
    bias_activation_fusion: False
      # converter_type: "Qwen2ForCausalLM"
    tensor_model_parallel_size: 4
    expert_tensor_parallel_size: 1
    expert_model_parallel_size: 8
    pipeline_model_parallel_size: 1
    num_layers_in_first_pipeline_stage: null
    num_layers_in_last_pipeline_stage: null
    context_parallel_size: 4
    pipeline_dtype: ${policy.precision}
    sequence_parallel: true
    freeze_moe_router: true
      # moe_router_dtype: "fp64"
    moe_router_dtype: "fp32"
    moe_router_load_balancing_type: "none" # "seq_aux_loss" causes logprob error divergence for grpo
    moe_router_bias_update_rate: 1e-3
    moe_permute_fusion: true
    moe_enable_deepep: false
    moe_token_dispatcher_type: "alltoall"
    moe_aux_loss_coeff: 0.0
    moe_router_enable_expert_bias: true
    #gives ~20% training perf speedup with sequence packing
    apply_rope_fusion: True
    defer_fp32_logits: True
    track_moe_metrics: True
    moe_per_layer_logging: True
    do_not_average_loss: true
    cp_normalize: true
    calculate_per_token_loss: true
    scale_loss_by_dp_cp_size: false # setting it to 0 will maximize performance, but it might lead to OOMs, while setting it to 2 to minimize the peak memory usage to avoid OOMs

    optimizer:
      optimizer: "adam"
      lr: ${policy.lr}
      min_lr: ${policy.min_lr}
      weight_decay: ${policy.weight_decay}
      bf16: true  # must be true to avoid checkpoint load error
      fp16: false
      params_dtype: "float32"

      #adam
      adam_beta1: 0.9
      adam_beta2: 0.98
      adam_eps: 1e-8

      #sgd
      sgd_momentum: 0.9

      #distributed optimizer
      use_distributed_optimizer: true
      use_precision_aware_optimizer: true

      # clip_grad: ${policy.max_grad_norm}

      # optimizer cpu offload
      optimizer_cpu_offload: false
      optimizer_offload_fraction: 0.0

    scheduler:
      start_weight_decay: ${policy.megatron_cfg.optimizer.weight_decay}
      end_weight_decay: ${policy.megatron_cfg.optimizer.weight_decay}
      weight_decay_incr_style: "constant"
      lr_decay_style: "cosine"
      lr_decay_iters: ${sft.max_num_steps}
      lr_warmup_iters: 0
      lr_warmup_init: 1.0e-6

    distributed_data_parallel_config:
      grad_reduce_in_fp32: false
      overlap_grad_reduce: true
      overlap_param_gather: true
      average_in_collective: true
      data_parallel_sharding_strategy: "optim_grads_params"

  dynamic_batching:
    enabled: false


  sequence_packing:
    enabled: True
    train_mb_tokens: ${mul:${policy.max_total_sequence_length}, ${policy.train_micro_batch_size}}
    algorithm: "modified_first_fit_decreasing"
    sequence_length_round: 64
    logprob_mb_tokens: ${mul:${policy.max_total_sequence_length}, ${policy.train_micro_batch_size}}
  #If this value is set to null, it will be automatically assigned in the code.
  make_sequence_length_divisible_by: null
  max_grad_norm: null

  optimizer:
    name: "torch.optim.AdamW"
    kwargs:
      lr: ${policy.lr}
      weight_decay: ${policy.weight_decay}
      betas: [0.9, 0.98]
      eps: 1e-8
      # when using Dtensor, we need to set foreach
      # and fused to False
      foreach: False
      fused: False

  scheduler:
  - name: "torch.optim.lr_scheduler.LinearLR"
    kwargs:
      start_factor: 1.0
      end_factor: 1.0
      total_iters: 1   # must be >=1, here it keeps LR constant
  - name: "torch.optim.lr_scheduler.CosineAnnealingLR"
    kwargs:
      T_max: ${sft.max_num_steps}      # total training steps
      eta_min: ${policy.lr}   # set min_lr = initial_lr -> constant schedule
  - milestones: [0]  # required to avoid config errors


data:
  max_input_seq_length: ${policy.max_total_sequence_length}
  dataset_name: prompt_response_dataset
  add_bos: false
  add_eos: false
  add_generation_prompt: false
  input_key: input
  output_key: output
  force_reprocess: false
  shuffle: true
  num_workers: 10

logger:
  log_dir: "logs"  # Base directory for all logs
  num_val_samples_to_print: 0 # Number of validation samples to pretty print on terminal
  wandb_enabled: false
  tensorboard_enabled: false
  mlflow_enabled: false  # Disable MLflow logging
  monitor_gpus: true  # If true, will monitor GPU usage and log to wandb and/or tensorboard
  swanlab_enabled: false # Disable SwanLab logging
  wandb:
    project: "grpo-dev"
    name: "grpo-dev-logger"
  tensorboard: {}
  mlflow:
    experiment_name: "grpo-dev"
    run_name: "grpo-dev-logger"
  gpu_monitoring:
    collection_interval: 10  # How often to collect GPU usage metrics (in seconds)
    flush_interval: 10  # How often to flush GPU usage metrics to the loggers (in seconds)

cluster:
  gpus_per_node: 8
  num_nodes: 32
