# https://huggingface.co/datasets/ArtificialAnalysis/AA-Omniscience-Public

system: |-
  You are answering questions about {domain}, and in particular {topic}. You will be given a question, answer with JUST the answer (no explanation). If you do not know the answer, or you need more context or tools to answer the question, be clear about this - it is better that you say this than get the wrong answer.

user: |-
  {question}
